package Modelos;
// Generated 24-nov-2023 0:46:43 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Articulos generated by hbm2java
 */
public class Articulos  implements java.io.Serializable {


     private String codarticulo;
     private Familias familias;
     private String nomarticulo;
     private double precio;
     private Set facturases = new HashSet(0);

    public Articulos() {
    }
	
    public Articulos(String codarticulo, Familias familias) {
        this.codarticulo = codarticulo;
        this.familias = familias;
    }
    public Articulos(String codarticulo, Familias familias, String nomarticulo, double precio, Set facturases) {
       this.codarticulo = codarticulo;
       this.familias = familias;
       this.nomarticulo = nomarticulo;
       this.precio = precio;
       this.facturases = facturases;
    }
   
    public String getCodarticulo() {
        return this.codarticulo;
    }
    
    public void setCodarticulo(String codarticulo) {
        this.codarticulo = codarticulo;
    }
    public Familias getFamilias() {
        return this.familias;
    }
    
    public void setFamilias(Familias familias) {
        this.familias = familias;
    }
    public String getNomarticulo() {
        return this.nomarticulo;
    }
    
    public void setNomarticulo(String nomarticulo) {
        this.nomarticulo = nomarticulo;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }

    public void addFactura(Facturas factura) {
        this.facturases.add(factura);
    }
    
    public ArrayList<Facturas> getListFacturas(){
        ArrayList<Facturas> lista = new ArrayList<>(this.facturases);
        return lista;
    }

    @Override
    public String toString() {
        return "Articulos{" + "codarticulo=" + codarticulo + ", familias=" + familias + ", nomarticulo=" + nomarticulo + ", precio=" + precio + ", facturases=" + facturases + '}';
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 47 * hash + Objects.hashCode(this.codarticulo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Articulos other = (Articulos) obj;
        if (!Objects.equals(this.codarticulo, other.codarticulo)) {
            return false;
        }
        return true;
    }
    
    
}


