package Modelos;
// Generated 24-nov-2023 0:46:43 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/**
 * Familias generated by hbm2java
 */
public class Familias  implements java.io.Serializable {


     private String codfamilia;
     private String nomfamilia;
     private Set articuloses = new HashSet(0);

    public Familias() {
    }

	
    public Familias(String codfamilia) {
        this.codfamilia = codfamilia;
    }
    public Familias(String codfamilia, String nomfamilia, Set articuloses) {
       this.codfamilia = codfamilia;
       this.nomfamilia = nomfamilia;
       this.articuloses = articuloses;
    }
   
    public String getCodfamilia() {
        return this.codfamilia;
    }
    
    public void setCodfamilia(String codfamilia) {
        this.codfamilia = codfamilia;
    }
    public String getNomfamilia() {
        return this.nomfamilia;
    }
    
    public void setNomfamilia(String nomfamilia) {
        this.nomfamilia = nomfamilia;
    }
    public Set getArticuloses() {
        return this.articuloses;
    }
    
    public void setArticuloses(Set articuloses) {
        this.articuloses = articuloses;
    }

    public void addArticulo(Articulos articulo) {
        this.articuloses.add(articulo);
    }
    
    public void removeArticulo(Articulos articulo) {
        this.articuloses.remove(articulo);
    }

    public ArrayList getListArticulos() {
        ArrayList<Articulos> lista = new ArrayList<>(this.articuloses);
        return lista;
    }
}


